### ISSUE TITLE
CH341 USB Serial to RS485 with GatewayOS on Raspberry Pi 4 

### ISSUE THREAD

**Issue by Orience** [chirpstack/chirpstack-gateway-os#110]
- [ x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-os/issues) of this repository and believe that this is not a duplicate.

## What happened?
I am currently testing my Raspberry Pi  4 Gateway with USB Serial to rs485 connector. The Rpi4 detect the usb , but cant access it. I try to install the kmod-usb-serial-ch341 , but it said kernel is not compatible. I saw that kmod-usb-serial and kmod-usb-serial-ftdi was installed.
## What did you expect?
I want to install the kmod-usb-serial-ch341 and access the USB serial. This rs485 is for a satellite terminal where data will be parse from the gateway and send through rs485 to the satellite terminal. 

## Steps to reproduce this issue

Steps:

1.Install kmod-usb-serial-341
2.
3.
4.

## Could you share your log output?

```shell

```

## Your Environment

| Component             | Version |
| ----------------------| ------- |
| ChirpStack Gateway OS |  4.3.2  |

**Comment by brocaar** [comment]
Most packages can be installed from the OpenWrt package repo, but you are right this does not work for kernel modules, since there is a slight (version) difference between the GW OS kernel version vs the OpenWrt released kernel.

Since this is quite a specific use-case, I'm not sure if it makes sense to include this in the pre-compiled images (currently I have no use-case for it nor I have the hardware for testing this). However, it should be quite easy to compile a custom ChirpStack Gateway OS image with the kernel-modules that you need.

Please see the README.md:

https://github.com/chirpstack/chirpstack-gateway-os

After setting up your environment and switching to the correct config, you should be able to do a `make menuconfig` to enable the kernel modules that you need, after which you can generate your own image using `make`.

Does that work for you?

**Comment by Orience** [comment]
Thanks brocaar for the guide. I was able to use the Usb serial connector with the custom compiled image.
